migration:
  createNewInstancesTarget: old
clusters:
  clusters:
    old:
      zeebeGrpc: http://localhost:26500
      zeebeRest: http://localhost:8088
#      auth-url: https://old.YOURDOMAIN.de:443/auth/realms/camunda-platform/protocol/openid-connect/token
#      client-id: zeebe
#      client-secret: OldSecret
    new:
      zeebeGrpc: http://localhost:26501
      zeebeRest: http://localhost:8089
#      auth-url: https://new.YOURDOMAIN.de:443/auth/realms/camunda-platform/protocol/openid-connect/token
#      client-id: zeebe
#      client-secret: NewSecret